# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np
arr=np.zeros(100)
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [7]:
arr=np.ones(100)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [8]:
arr=np.linspace(3,3,100, endpoint=False)
arr

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [195]:
np.add #shift+tab

<ufunc 'add'>

#### 5. Поменять 2 строки в матрице

In [12]:
b=np.eye(5)
b[[0,2]]=b[[2,0]]
b

array([[0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 6. Создать вектор со значениями от 10 до 100

In [16]:
b=np.arange(10,101, 1)
b

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [17]:
b=np.arange(10,101, 1)
np.flip(b)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [39]:
c=np.arange(0,16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [5]:
arr = np.arange(1,6)
step = 4
newArr = np.zeros(len(arr) + (len(arr)-1)*(step - 1), int)
newArr[::step] = arr
print(newArr)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 10. Создать 3x3 единичную матрицу

In [34]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [54]:
np.random.random((3,3,3))

array([[[0.240061  , 0.99245951, 0.87860965],
        [0.8938293 , 0.05805035, 0.45946458],
        [0.21573556, 0.85197883, 0.01803167]],

       [[0.65495706, 0.11783871, 0.27177522],
        [0.82099005, 0.90726881, 0.76507709],
        [0.56564205, 0.92431683, 0.00180096]],

       [[0.98261524, 0.13890217, 0.18177147],
        [0.71972282, 0.58134511, 0.80583331],
        [0.23863997, 0.30082713, 0.6331996 ]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [61]:
a=np.random.random((10,10))
minimum=a.min()
maximum=a.max()
print('min:', minimum, '\n', 'max:',maximum)

min: 0.003011447250701793 
 max: 0.9605776284322994


13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [71]:
a=np.random.random((30))
avg=a.mean()
avg

0.46295957302349305

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [14]:
c=np.ones((5,5))
c[1:4,1:4]=0
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [ ]:
#ну раз не идет в зачет...

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [50]:
c=np.ones((5,5))
c[2,1]=2
c[3,2]=2
c[4,3]=4
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 4., 1.]])

17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [51]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [57]:
a=np.arange(0,6*7*8,1).reshape(6,7,8)
ind=np.where(a==100)
ind

(array([1], dtype=int64), array([5], dtype=int64), array([4], dtype=int64))

19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [117]:
a=np.array([(1,0),(0,1)])
np.tile(a,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

20. Перемножить матрицы 5x3 и 3x2

In [109]:
a=np.arange(0,5*3,1).reshape(5,3)
b=np.arange(0,3*2,1).reshape(3,2)
np.dot(a,b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [144]:
arr=np.random.random((5,5))
arr=np.multiply(arr,10)
arr[(arr>3) & (arr < 8)] *= -1
arr


array([[ 2.97686004, -3.44558289, -3.82962741, -3.75730895, -4.5870995 ],
       [ 8.90309607, -6.20781395,  1.50049749,  9.66190007,  0.80634149],
       [ 1.88486482,  0.34951127,  9.52993443, -7.29674084, -4.10226104],
       [-4.22015783,  8.37930035, -6.85993006, -5.72318378,  2.00934263],
       [ 1.53230013,  8.41670968,  9.22416138, -3.60667311, -6.77418274]])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [148]:
arr=np.random.randint(0,4,25).reshape(5,5)
arr

array([[3, 2, 3, 1, 0],
       [2, 2, 3, 3, 0],
       [3, 2, 3, 0, 3],
       [0, 1, 1, 3, 3],
       [1, 0, 1, 0, 3]])

#### 24. Есть генератор, сделать с его помощью массив

In [149]:
arr=np.random.randint(0,4,25).reshape(5,5)
arr

array([[3, 2, 1, 3, 2],
       [2, 2, 0, 3, 2],
       [3, 3, 0, 2, 3],
       [2, 1, 3, 1, 0],
       [3, 3, 0, 3, 3]])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [151]:
arr=np.random.random((10))
arr

array([0.40994537, 0.40859078, 0.02416061, 0.82728413, 0.26115614,
       0.34393064, 0.98236305, 0.44500963, 0.09458745, 0.78349891])

#### 26. Отсортировать вектор

In [156]:
arr=np.random.random((10))
arr.sort()
arr

array([0.08162842, 0.17815424, 0.20947006, 0.33722824, 0.38019484,
       0.55807291, 0.66576257, 0.76399995, 0.83214566, 0.95299836])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [157]:
arr1=np.random.random((10))
arr2=np.random.random((10))
print(np.array_equal(arr1,arr2))

False


#### 28. Сделать массив неизменяемым

In [162]:
arr1=np.full((1,6),2)
arr1

array([[2, 2, 2, 2, 2, 2]])

#### 29. Найти n наибольших значений в массиве

In [183]:
n=np.random.randint(1,10,1)
arr=np.random.random((10))
arr.sort()
arr=arr[::-1]
arr[0:n[0]]

array([0.9081976 , 0.76448706, 0.53875869, 0.41367412, 0.37610229])

#### 30. Заменить максимальный элемент на ноль

In [191]:
arr=np.random.random((10))
arr[np.where(arr==arr.max())]=0
arr

array([0.87389476, 0.20057536, 0.43430392, 0.54283345, 0.26679436,
       0.09840906, 0.83429672, 0.        , 0.91661821, 0.89436979])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
#не понял условие задания

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [37]:
arr1 = np.arange(1,np.random.randint(1,10,1)[0])
arr2 = arr1 + np.random.randint(1,8,1)[0]
denominator=np.subtract.outer(arr1,arr2)
denominator=abs(denominator)
arr3 = 1.0 / denominator
arr3

array([[0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.5       , 0.33333333, 0.25      , 0.2       ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [199]:
np.iinfo(np.int16) # и т.д для каждого типа 

iinfo(min=-32768, max=32767, dtype=int16)

#### 34. Напечатать все значения в массиве

In [205]:
arr=np.random.random((10))
arr

array([0.75912219, 0.65612571, 0.26235335, 0.01398258, 0.64367659,
       0.67715657, 0.4766881 , 0.30371667, 0.80078085, 0.66967656])

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [220]:
n=np.random.random((1))[0]
arr=np.random.random((10))
val=np.abs(arr - n)
smallest_diff=val.argmin()
closest=arr[smallest_diff]
print('Рандомное число:',n)
print('\nМассив:', arr)
print('\nБлижайшее:', closest)


Рандомное число: 0.8198609644051117

Массив: [0.199099   0.81098797 0.72333876 0.09569935 0.00624872 0.08591302
 0.04906511 0.03189685 0.79178636 0.74924148]

Ближайшее: 0.8109879749945665


#### 36. Преобразовать массив из float в int

In [229]:
arr=np.random.random((10))
arr=np.multiply(arr,10)
print('до:', arr)
print('после',arr.astype(int))

до: [9.35068496 3.98508802 8.2294111  9.78420174 7.66373099 1.74060621
 0.42512434 2.41889665 9.98798734 7.14917889]
после [9 3 8 9 7 1 0 2 9 7]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [ ]:
np.nditer

#### 38. Случайно расположить p элементов в 2D массив

In [3]:
p=np.random.randint(1,10,1)[0]
arr=np.zeros((p,p))
for x in range(0,p+1):
    isNotFree=True
    while isNotFree==True:
        x=np.random.randint(1,p,1)[0]
        y=np.random.randint(1,p,1)[0]
        if arr[x,y]!=5:
            arr[x,y]=5
            isNotFree=False
print('p=',p)
print(arr)

p= 8
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 5. 0.]
 [0. 0. 0. 5. 0. 5. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 5. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. Отнять среднее из каждой строки в матрице

In [45]:
arr=np.arange(25).reshape(5,5)
mid=arr.mean()
arr=arr-mid
arr

array([[-12., -11., -10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.,  -4.,  -3.],
       [ -2.,  -1.,   0.,   1.,   2.],
       [  3.,   4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.,  12.]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [69]:
n=np.random.randint(2,10,1)[0]
arr = np.random.randint(0,10,(n,n))
print('n=',n)
print(arr[arr[:,n-1].argsort()])

n= 7
[[7 0 5 0 2 1 1]
 [7 3 9 2 2 4 1]
 [9 7 2 5 6 4 3]
 [6 4 2 4 1 0 3]
 [4 2 6 0 6 4 4]
 [5 7 5 6 3 6 5]
 [7 3 1 9 4 3 6]]


41. Определить, есть ли в 2D массиве нулевые столбцы

In [110]:
arr = np.random.randint(0,2,(3,3))
print((~arr.any(axis=0)).any())
print(arr)

True
[[1 0 0]
 [0 0 0]
 [0 1 0]]


 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [11]:
arr1=np.random.random(10)
arr2=np.array([2,4,8])
arr1+= np.bincount(arr2, minlength=len(arr1))
arr1

array([0.45312371, 0.16372797, 1.74604318, 0.698463  , 1.12866102,
       0.28221754, 0.88237942, 0.7459329 , 1.2397303 , 0.41739034])

43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
#не понял

44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [18]:
arr = np.random.randint(0, 10, (3, 3, 3, 3))
sum = arr.reshape(arr.shape[:-2] + (-1,)).sum(axis=-1)
print('массив:\n',arr)
print('Сумма:\n', sum)

массив:
 [[[[1 0 2]
   [4 6 2]
   [6 2 3]]

  [[1 8 7]
   [1 0 4]
   [9 6 4]]

  [[6 0 8]
   [7 9 3]
   [8 1 7]]]


 [[[1 2 7]
   [5 0 3]
   [5 9 7]]

  [[3 0 2]
   [0 4 9]
   [7 5 7]]

  [[0 5 6]
   [5 8 7]
   [9 2 5]]]


 [[[0 8 2]
   [2 3 3]
   [6 4 0]]

  [[1 8 4]
   [8 6 0]
   [7 7 6]]

  [[5 4 8]
   [7 7 6]
   [5 2 9]]]]
Сумма:
 [[26 40 49]
 [39 37 47]
 [28 47 53]]
